-- ADT Stock V173 — سجل سعر الشراء
-- شغّل هذا الملف مرة واحدة في Supabase SQL Editor قبل استخدام «سجل سعر الشراء».

create table if not exists public.adt_buy_price_history (
  id bigint generated by default as identity primary key,
  team_id text not null,
  product_id text not null,
  product_name text not null default '',
  old_price numeric(18,4),
  new_price numeric(18,4) not null,
  supplier_name text not null default '',
  changed_by text not null default '',
  changed_by_user_id text not null default '',
  changed_at timestamptz not null default now()
);

create index if not exists adt_buy_price_history_team_product_idx
  on public.adt_buy_price_history(team_id, product_id, changed_at desc);

alter table public.adt_buy_price_history enable row level security;
revoke all on table public.adt_buy_price_history from anon, authenticated;

create or replace function public.adt_buy_price_history_record(
  p_team_id text,
  p_user_id text,
  p_product_id text,
  p_product_name text,
  p_old_price numeric,
  p_new_price numeric,
  p_actor_name text,
  p_supplier_name text default ''
)
returns boolean
language plpgsql
security definer
set search_path to 'public','extensions'
as $function$
begin
  if not public.adt_is_primary_manager(p_team_id,p_user_id) then
    return false;
  end if;
  if p_product_id is null or btrim(p_product_id) = '' or p_new_price is null or p_new_price < 0 then
    return false;
  end if;
  if p_old_price is not null and p_old_price = p_new_price then
    return true;
  end if;
  insert into public.adt_buy_price_history(
    team_id,product_id,product_name,old_price,new_price,supplier_name,changed_by,changed_by_user_id
  ) values (
    p_team_id,p_product_id,coalesce(p_product_name,''),p_old_price,p_new_price,coalesce(p_supplier_name,''),coalesce(p_actor_name,'مدير'),p_user_id
  );
  return true;
end;
$function$;

revoke all on function public.adt_buy_price_history_record(text,text,text,text,numeric,numeric,text,text) from public;
grant execute on function public.adt_buy_price_history_record(text,text,text,text,numeric,numeric,text,text) to anon, authenticated;

create or replace function public.adt_buy_price_history_fetch(
  p_team_id text,
  p_user_id text,
  p_product_id text
)
returns table(
  id bigint,
  product_name text,
  old_price numeric,
  new_price numeric,
  supplier_name text,
  changed_by text,
  changed_at timestamptz
)
language plpgsql
stable
security definer
set search_path to 'public','extensions'
as $function$
begin
  if not public.adt_is_primary_manager(p_team_id,p_user_id) then
    return;
  end if;
  return query
    select h.id,h.product_name,h.old_price,h.new_price,h.supplier_name,h.changed_by,h.changed_at
    from public.adt_buy_price_history h
    where h.team_id=p_team_id and h.product_id=p_product_id
    order by h.changed_at desc,h.id desc
    limit 250;
end;
$function$;

revoke all on function public.adt_buy_price_history_fetch(text,text,text) from public;
grant execute on function public.adt_buy_price_history_fetch(text,text,text) to anon, authenticated;

notify pgrst, 'reload schema';
